name: Run EHWO Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,6,12,18 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run EHWO Script
        run: python EHWO.py

      - name: Create credentials.json
        run: echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > credentials.json
